[package]
name = "zed-numscript"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.2.0"

[build-dependencies]
toml = "*"
serde = { version = "*", features = ["derive"] }
anyhow = "*"
